#
## Copyright (C) 2013 CZ.NIC z.s.p.o. <michal.vaner@nic.cz>
#
## This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
# #
#


include $(TOPDIR)/package/packages/net/ucollect-core/Makefile.common

$(eval $(call UCOLLECT_PLUGIN,buckets,8))

$(eval $(call BuildPackage,ucollect-buckets))
