#!/bin/sh

set -ex

/etc/uci-defaults/unbound && rm /etc/uci-defaults/unbound

/etc/init.d/unbound enable || true
sleep 2
/etc/init.d/dnsmasq restart
sleep 20 # Cooldown for above (problems in times of reinstall)
# Also in case we fail to restart because the kernel did not have time to clean
# up the sockets, try to wait a little and try it again.
/etc/init.d/unbound restart || \
	( sleep 10 ; /etc/init.d/unbound restart ) || \
	( sleep 30 ; /etc/init.d/unbound restart )
