Turris-os-packages repository workflow
======================================

Before you start reading please be sure that you have read and understood workflow
for https://gitlab.labs.nic.cz/turris/turris-build/blob/master/WORKFLOW.adoc[turris-build].
This work-flow is referencing it as this repository is used as part of release
cycle of that one.


Primary (protected) branches of this repository
-----------------------------------------------

There are two primary branches in this repository

*stable*:: is default branch and contains latest stable version with possible few
fixes on top of it. This branch is used in *hbk* branch in turris-build
repository.

*develop*:: is branch we use to integrate latest changes and improvements in this
repository. It is used in *hbl* and *hbd* branches in turris-build repository.


Overview of flow in this repository
-----------------------------------

Branch *stable* is parent branch for all work in this repository. Branch
*develop* is forked off of it initially.
..................................................................................
           develop            stable
              _________________/|
              |                 |<- v5.1.0
              |                 |
..................................................................................
Any new feature is forked off from *develop* branch.
..................................................................................
feature/foo   |                 |
     ________/|                 |
     |        |                 |
     |        |                 |
..................................................................................
And later merged back to *develop* branch when it is finished and tested.
..................................................................................
     |        |                 |
     |_______ |                 |
             \|                 |
              |                 |
..................................................................................
If bug is discovered in feature then new branch based on *develoop* is created
to fix it.
..................................................................................
 bugfix/foo   |                 |
     ________/|                 |
     |        |                 |
     |        |                 |
..................................................................................
That is later merged to *develop* the same way as original feature.
..................................................................................
     |        |                 |
     |_______ |                 |
             \|                 |
              |                 |
..................................................................................
When problem is discovered in current stable version then branch to fix it is
forked off *stable* branch.
..................................................................................
              |   hotfix/foo    |
              |        ________/|
              |        |        |
              |        |        |
..................................................................................
And later merged back to both *stable* and *develop* branch when finished and
tested.
..................................................................................
              |        |        |
              | _______|_______ |
              |/               \| <- v5.1.1
              |                 |
..................................................................................
To make new major or minor release (that is release containing latest Turris
changes and improvements) we merge *develop* to *stable* branch.
..................................................................................
              |                |
              |_______________ |
                              \|
                               | <- v5.2.0
..................................................................................
This makes them effectively in sync and flow starts from beginning just as we
would fork new *develop* branch.


Branch naming convention
------------------------

For quick orientation of maintainers in repository stable naming convention is
required. Depending on what you are planning to do you can create new branch with
name prefixed with one of following:

*hotfix/*:: This is fix for problem discovered in *stable*. It has to be based on
*stable* branch and merged to both *develop* and *stable* branch.

*bugfix/*:: This is fix for problem not affecting *stable*. It has to be
based on *develop* branch and merged only to *develop* only.

*feature/*:: New feature based on *develop* branch. This can be new package
or new version of some package with tweaks to packages. It is merged only back
to *develop* branch.

*refactor/*:: This has same flow as feature but does not change packages
versions or affects anything that requires package version change.

*hack/*:: This is feature that is to be reverted in future. This should never be
merged as fast-forward to ease future revert.

After this prefix you should add short name for what you are about to do.
Acceptable is for example name of package or feature you are about to implement.
Please do not use issue numbers of nothing saying generic words (such as:
hotfix/problem).


Operations performed by developers
----------------------------------

Developer is anyone who wants to contribute to this repository. Developers are not
allowed to merge to primary branches (*stable* and *develop*) and have to ask
maintainers to do so (submit pull or merge request).

=== Implementing fix for problem in *stable* (hotfix)
You have to base your work on latest commit in *stable*. For example:
[,sh]
----------------------------------------------------------------------------------
git fetch
git checkout -b hotfix/FOO origin/stable
----------------------------------------------------------------------------------

Also not that you might and will be asked by maintainer to possibly rebase your
changes on latest *stable* commit.
[,sh]
----------------------------------------------------------------------------------
git fetch
git rebase origin/stable
----------------------------------------------------------------------------------

=== Implementing new feature or fixing something not affecting *stable* (bugfix/feature/refactor/hack)
You have to base you work on latest commit in *develop* branch. For example:
[,sh]
----------------------------------------------------------------------------------
git fetch
git checkout -b bugfix/FOO origin/develop
----------------------------------------------------------------------------------

Same as in case of hotfixes you might be asked by maintainer to rebase your work
on latest commit in *develop* branch.
[,sh]
----------------------------------------------------------------------------------
git fetch
git rebase origin/develop
----------------------------------------------------------------------------------


Operations performed by maintainers
-----------------------------------

There are few well informed maintainers who are well educated with git-craft and
with flow of this repository that they are allowed to manage *stable* and
*develop* branch. For those not so lucky and new in this craft there is following
list of operations commonly performed by maintainer.

=== Merging hotfix

Hotfixes should always be merged to both *stable* and *develop* branch.
[,sh]
----------------------------------------------------------------------------------
git checkout stable
git merge --ff-only --gpg-sign hotfix/foo
git checkout develop
git merge --no-ff --gpg-sign hotfix/foo
git push origin stable develop :hotfix/foo
----------------------------------------------------------------------------------

Hotfix merge to *stable* should always be clean. That means that there should be
no merge conflicts (ensured by requiring fast forward only). This is to ensure
that stable won't be broken by merge. When that can't be done rebase to latest
changes has to be performed. The maintainer can either ask author or do it by
himself. 

There is possibility that hotfix is not required in *develop* branch because it
can be fixed by some other means or was already fixed by some previous feature. In
such case it should be merged nonetheless to ease future merge of *develop* back
to *stable*. For doing merge without merging changes you can use git merge
strategy `ours`.
[,sh]
----------------------------------------------------------------------------------
git checkout develop
git merge --strategy=ours --gpg-sign hotfix/foo
----------------------------------------------------------------------------------
Or you can revert some changes and merge rest.
[,sh]
----------------------------------------------------------------------------------
git revert HEAD^
git checkout develop
git merge --no-ff --gpg-sign hotfix/foo
----------------------------------------------------------------------------------

=== Merging new feature, bugfix and others

Branches with new features, bugfixes, refactoring or hacks are merged to *develop*
branch. This merge should be without conflict as well to prevent bugs created by
merge skipping testing. On merge conflict it should be evaluated, rebased on
latest commit in *develop* (to resolve conflict) and test again before merge.
[,sh]
----------------------------------------------------------------------------------
git checkout develop
git merge --ff-only --gpg-sign feature/foo
git push origin develop :feature/foo
----------------------------------------------------------------------------------

=== Merging and reverting hack

Hacks are intended to be present only temporally and so it is expected that in
future we want them reverted and that way removed. This means that hacks are
merged as an exception with merge commit instead of doing fast-forward merge.
[,sh]
----------------------------------------------------------------------------------
git checkout develop
git merge --ff-only --gpg-sign feature/foo
git push origin develop :feature/foo
----------------------------------------------------------------------------------

Later hack, thanks to merge commit, can be just reverted by locating appropriate
merge commit hash and reverting it. Note that this is considered as refactor and
new appropriate merge request should be created and review should be performed.
[,sh]
----------------------------------------------------------------------------------
git checkout -b refactor/FOO origin/develop
git revert -m 1 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
----------------------------------------------------------------------------------

=== Tagging version of released Turris OS

This happens on same time as in turris-build repository. Maintainer creating tag
in turris-build has to create tag in this repository as well.

First found out exact hash for git hash in this repository from tag in
turris-build. Then you can create appropriate tag.
[,sh]
----------------------------------------------------------------------------------
git tag -s -m "Turris OS packages for Turris OS X.X.X" vX.X.X HASH
git push --tags origin vX.X.X
----------------------------------------------------------------------------------
// TODO: we should implement script that exactly tags commit the same way as
// in turris-build.

=== Preparing next minor or major version of Turris OS

On new major or minor release of Turris OS we have to move all development changes
to stable. This is done by merging *develop* to *stable* in appropriate moment
against turris-build repository. This operation is required to be done anytime
merge of *hbl* is performed to *hbk*.

If all previous operations were performed correctly then we can now do clean
recursive merge (without merge conflicts).
[,sh]
----------------------------------------------------------------------------------
git checkout stable
git merge --no-ff --gpg-sign develop
git push origin stable
----------------------------------------------------------------------------------

Tips for developers and maintainers
-----------------------------------

This is collection of various tips and primarily configuration options you can use
to simplify commands described in this flow.

Sign commits and tags with GPG without using `--gpg-sign` and `-s`::
You can configure global or local git option `commit.gpgSign` and `tag.gpgSign`.
[,sh]
----------------------------------------------------------------------------------
git config --local commit.gpgSign true
git config --local tag.gpgSign true
----------------------------------------------------------------------------------

Sign commits and tags with specific PGP key::
If you have more than one PGP key (for example different for personal and work
identity) then you can specify exactly which should be always used in git
configuration option `user.signingKey`. Value of that option is fingerprint of
your PGP key.
[,sh]
----------------------------------------------------------------------------------
git config --local user.signingKey "XXXXXXXXXXXXXXXX"
----------------------------------------------------------------------------------
