#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=10
EXTRA_COMMANDS="status"

status() {
  ps | grep -v grep | grep '/usr/bin/sentinel-dynfw-client' &>/dev/null
}

start_service() {
  status && { echo "Service already running" >&2 ; exit 1; }
  get_cert || { echo "Can't download server certificate" >&2 ; exit 1; }
  /usr/sbin/ipset create turris-sn-wan-input-block hash:ip -exist
  /usr/sbin/iptables -I input_wan_rule -m conntrack --ctstate NEW -m set --match-set turris-sn-wan-input-block src -m mark ! --mark 0x10/0x10 -j DROP
  procd_open_instance
  procd_set_param command /usr/bin/python3 /usr/bin/sentinel-dynfw-client
  procd_set_param respawn ${respawn_threshold:-600} ${respawn_timeout:-5} ${respawn_retry:-5}
  procd_close_instance
}

stop_service() {
  /usr/sbin/iptables -D input_wan_rule -m conntrack --ctstate NEW -m set --match-set turris-sn-wan-input-block src -m mark ! --mark 0x10/0x10 -j DROP
}


get_cert() {
  [ -f /tmp/sentinel_server.key ] && return 0
  curl -f -s https://repo.turris.cz/sentinel/dynfw.pub -o /tmp/sentinel_server.key
  #TODO: add certificate gpg verification
}
