#!/bin/sh

if [ ! -d /proc ]; then mkdir /proc; fi
if [ ! -d /dev ]; then mkdir /dev; fi
if [ ! -d /sys ]; then mkdir /sys; fi
if [ ! -d /mnt ]; then mkdir /mnt; fi

mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs -o size=1M tmpfs /dev
mkdir /dev/pts
mount -t devpts none /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
mount -t tmpfs -o size=300M,mode=0755 tmpfs /tmp

