#!/bin/sh /etc/rc.common
START=99
STOP=00

VERSION=@VERSION@

start() {
	if [ "0$(cat /etc/nor-version 2>/dev/null)" -ne $VERSION ] && [ "$(uname -m)" = ppc ]; then
		( for i in 0 1 2 3; do
			mtd verify /usr/share/nor-update/turris/mtd$i /dev/mtd$i || mtd -e /dev/mtd$i write /usr/share/nor-update/turris/mtd$i /dev/mtd$i
		done
		echo $VERSION > /etc/nor-version
		sync
		) &
	fi
}

stop() {
	echo "Nothing to do"
}
