#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10
EXTRA_COMMANDS="firewall"

DEFAULT_LOCAL_PORT=2525
DEFAULT_FIREWALL_ZONE="wan"

firewall_drop() {
	iptables -t nat -S | sed -n '/--comment "!haas:/s/^-A//p' | while read -r rule; do
		eval "iptables -t nat -D $rule"
	done
	ip6tables -t nat -S | sed -n '/--comment "!haas:/s/^-A//p' | while read -r rule; do
		eval "ip6tables -t nat -D $rule"
	done
}

iptb_insert() {
	local iptb="$1"
	shift
	"$iptb" -C "$@" 2>/dev/null || "$iptb" -I "$@"
}

iptb_set() {
	local iptb="$1"
	local chain="$2"
	local comment="$3"
	shift 3
	# Note: variable port is from caller
	iptb_insert "$iptb" "$chain" -t nat "$@" -p tcp -m tcp --dport 22 -m comment --comment "!haas:dnat$comment" -j DNAT --to-destination ":$port"
	iptb_insert "$iptb" "$chain" -t nat "$@" -p tcp -m tcp --dport 22 -m comment --comment "!haas:mark$comment" -j MARK --set-mark 0x10
}

_ip6fw_network_handle() {
	local interface="$1"
	(
	config_load network
	config_get ifname "$interface" ifname
	[ -n "$ifname" ] || return
	iptb_set ip6tables PREROUTING ":$ifname" -i "$ifname"
	)
}

_ip6fw_zones_handle() {
	local zone="$1"
	local zone_name
	config_get zone_name "$zone" name
	[ "$zone_name" = "$fw_zone" ] || return
	config_list_foreach "$zone" network _ip6fw_network_handle
}

_firewall_zone() {
	local fw_zone="$1"
	# IPv4
	iptb_set iptables "zone_${fw_zone}_prerouting" ""
	# IPv6 (fw3 does not provide us with convenient chains so we have to filter interfaces on our own)
	(
	config_load firewall
	config_foreach _ip6fw_zones_handle zone
	)
}

firewall() {
	firewall_drop

	config_load haas
	local port fw_zone
	config_get port settings local_port "$DEFAULT_LOCAL_PORT"
	config_get fw_zone settings fw_zone
	if [ -n "$fw_zone" ]; then
		config_list_foreach settings fw_zone _firewall_zone
	else
		_firewall_zone "$DEFAULT_FIREWALL_ZONE"
	fi
}

start_service() {
	config_load haas
	local token log log_level port
	config_get token settings token ''
	config_get log settings log 'none'
	config_get log_level settings log_level 'warning'
	config_get port settings local_port "$DEFAULT_LOCAL_PORT"
	[ -n "$token" ] || {
		echo "Token not set. Please set HAAS token to allow it to start." >&2
		exit 1
	}

	firewall

	procd_open_instance
	procd_set_param command /usr/libexec/haas-proxy-start -n haas_proxy --log-level="$log_level" --device-token="$token" --port="$port"
	[ -z "$log" -o "$log" = "none" ] || procd_append_param command --log="$log"
	procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
	procd_set_param file /etc/config/haas
	procd_close_instance
}

stop_service() {
	firewall_drop
}
