#!/bin/sh

echo "CZ.NIC init"; echo

for i in /etc/rc.d/$1*; do
        [ -x $i ] && $i $2 2>&1
        RET=$?
        if [ $RET == 0 ]; then
                echo "$i        [done]"
        else
                echo "$i        [fail!]"
        fi        

done

