#!/bin/sh
DEVEL=""
while [ -n "$1" ]; do
    [ "x$1" \!= "x-d" ] || DEVEL="y"
    shift
done
if [ -n "$DEVEL" ]; then
    [ -f /usr/share/omnia/uboot-devel ] && \
    mtd verify /usr/share/omnia/uboot-devel /dev/mtd0 || \
    mtd -e /dev/mtd0 write /usr/share/omnia/uboot-devel /dev/mtd0
    [ -f /usr/share/rescue-image/image.fit.lzma ] &&
    mtd verify /usr/share/rescue-image/image.fit.lzma /dev/mtd1 || \
    mtd -e /dev/mtd1 write /usr/share/rescue-image/image.fit.lzma /dev/mtd1
else
    echo "No stable images yet!"
fi
