#!/bin/sh
modules="`cat /sys/devices/platform/soc/soc:internal-regs@*/*.spi/spi_master/spi*/spi*/module_topology | sed 's|[[:blank:]]|\n|g'`"

# First setup
if [ \! -f /etc/mox_modules ]; then

# Drop all network configuration
uci delete network.lan
uci delete network.wan

lans="$(echo $(cd /sys/class/net/; ls -d lan* 2> /dev/null))"
wan_if=""
lan_if=""

# If we have SFP, it is definitely WAN
if expr "$modules" : '.*sfp.*' > /dev/null; then
	wan_if=eth1
	lan_if="eth0 $lans"

# If we have switch, then CPU port is obviously WAN
elif expr "$modules" : '.*topaz.*' > /dev/null || expr "$modules" : '.*peridot.*' > /dev/null; then
	wan_if=eth0
	lan_if="$lans"

# If we have just one port, it has to be LAN
else
	lan_if="eth0"
fi

uci import << EOF
`uci export network`

config interface 'lan'
	option type 'bridge'
        option ifname '$lan_if'
        option proto 'static'
        option ipaddr '192.168.1.1'
        option netmask '255.255.255.0'

config interface 'wan'
        option ifname '$wan_if'
        option proto 'none'
EOF
uci commit
/etc/init.d/network restart

# Try dhcpp on LAN
sleep 5
if udhcpc -fqn -i br-lan; then
	uci set network.lan.proto=dhcp
	uci delete network.lan.ipaddr
	uci delete network.lan.netmask
	uci commit
fi
echo "$modules" > /etc/mox_modules

# Modules changes
elif [ "`cat /etc/mox_modules`" \!= "$modules" ]; then
	added="`echo "$modules" | comm -1 - /etc/mox_modules`"
	removed="`echo "$modules" | comm -1 - /etc/mox_modules`"
	TEXT="Your MOX HW configuration changed!"
	[ -z "$added" ] || TEXT="$TEXT You added `echo $added` module(s)."
	[ -z "$added" ] || TEXT="$TEXT You removed `echo $removed` module(s)."
	TEXT="$TEXT Make sure that your setup is correct or try factory reset for new setup."
	create_notification "$TEXT"
	if ( expr "$added" : '.*topaz.*' > /dev/null || expr "$added" : '.*peridot.*' > /dev/null ) && [ -n "`uci show network.lan`" ]; then
		for iface in `cd /sys/class/net/; ls -d lan* 2> /dev/null`; do
			grep $iface /etc/config/network > /dev/null || uci set network.lan.ifname="`uci get network.lan.ifname $iface`"
		done
	fi
fi
