#!/bin/sh
DEVEL=""
while [ -n "$1" ]; do
    [ "x$1" \!= "x-d" ] || DEVEL="y"
    shift
done
mtd verify /usr/share/mox/secure-firmware /dev/mtd0 || \
mtd -e /dev/mtd0 write /usr/share/mox/secure-firmware /dev/mtd0
if [ -n "$DEVEL" ]; then
    [ -f /usr/share/mox/uboot-devel ] && \
    mtd verify /usr/share/mox/uboot-devel /dev/mtd1 || \
    mtd -e /dev/mtd1 write /usr/share/mox/uboot-devel /dev/mtd1
    [ -f /usr/share/rescue-image/image.fit.lzma ] &&
    mtd verify /usr/share/rescue-image/image.fit.lzma /dev/mtd3 || \
    mtd -e /dev/mtd3 write /usr/share/rescue-image/image.fit.lzma /dev/mtd3
    mtd verify /boot/armada-3720-turris-mox.dtb /dev/mtd4 || \
    mtd -e /dev/mtd4 write /boot/armada-3720-turris-mox.dtb /dev/mtd4
else
    mtd verify /usr/share/mox/uboot /dev/mtd1 || \
    mtd -e /dev/mtd1 write /usr/share/mox/uboot /dev/mtd1
    mtd verify /usr/share/mox/rescue /dev/mtd3 || \
    mtd -e /dev/mtd3 write /usr/share/mox/rescue /dev/mtd3
    mtd verify /usr/share/mox/dtb /dev/mtd4 || \
    mtd -e /dev/mtd4 write /usr/share/mox/dtb /dev/mtd4
fi
