#!/bin/sh
[ "$BUTTON" = BTN_0 ] || exit 0
[ "$ACTION" = released ] || exit 0
if [ "$SEEN" -lt 4 ] || [ "$SEEN" -gt 60 ]; then
	reboot
else
	echo s > /proc/sysrq-trigger
	echo b > /proc/sysrq-trigger
fi
