#!/bin/sh
if grep -q '^/dev/mmcblk0p2 / btrfs' /proc/mounts; then
	mkdir -p /boot/tefi
	mount -t vfat /dev/mmcblk0p1 /boot/tefi
	cmp "$1"/boot/zImage /boot/tefi/zImage || cp "$1"/boot/zImage /boot/tefi/zImage
	cmp "$1"/boot/fdt /boot/tefi/fdt || cp "$1"/boot/fdt /boot/tefi/fdt
	umount /boot/tefi
fi
