#!/bin/sh
# Copyright (C) 2018 CZ.NIC z.s.p.o. (http://www.nic.cz/)

/etc/init.d/sentinel-dynfw-client status || exit 0

/usr/sbin/iptables -I input_wan_rule -m state --state NEW -m set --match-set turris-sn-wan-input-block src -m mark ! --mark 0x10/0x10 -j DROP || /usr/sbin/iptables -I input_wan_rule -m state --state NEW -m set --match-set turris-sn-wan-input-block src -m mark ! --mark 0x10/0x10 -j DROP
