#!/bin/sh

#    Copyright (c) 2015, CZ.NIC, z.s.p.o. (http://www.nic.cz/)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

## Settings
OUI_FILE="oui.db"

QRY="$1"

if [ -z "$QRY" ]; then
	echo "Usage error: Provide MAC address" >&2
	exit 1
fi

if [ ! -f "$OUI_FILE" ]; then
	echo "OUT DB file doesn't exists" >&2
	exit 2
fi

PREFIX="$(echo "$QRY" | sed -n 's/^\([0-9a-fA-F]\{2\}\)\([:\.-]\{0,1\}\)\([0-9a-fA-F]\{2\}\)\2\([0-9a-fA-F]\{2\}\)\2[0-9a-fA-F]\{2\}\2[0-9a-fA-F]\{2\}\2[0-9a-fA-F]\{2\}$/\1\3\4/p')"
[ -n "$PREFIX" ] || exit 3

grep -i "$PREFIX" "$OUI_FILE" 2> /dev/null | cut -d'|' -f2
