#!/bin/sh /etc/rc.common

USE_PROCD=1

start_service() {
  mkdir -p /var/log/suricata
  mkdir -p /var/run/suricata
  interface=$(uci -q get suricata.suricata.interface)
  [ "$interface" ] || interface=br-lan
  suricata_update_rules.sh -f
  procd_open_instance
  procd_set_param command /usr/bin/suricata -c /etc/suricata/suricata.yaml -i $interface --init-errors-fatal --pidfile /var/run/suricata/suricata.pid
  procd_close_instance
}
