#!/bin/sh

DEFAULT_RUNDIR=$(uci get resolver.kresd.rundir)
TMP_HINTS_CONFIG=$DEFAULT_RUNDIR/hints.tmp			#generated by kresd
TMP_HINTS_CONFIG_EMPTY=$DEFAULT_RUNDIR/hints_empty.tmp		#empty file to clear hints
TMP_HINTS_CONFIG_DYNAMIC=$DEFAULT_RUNDIR/hints_dynamic.tmp

TTY_PATH=$DEFAULT_RUNDIR/tty/$(pidof kresd)
LOCAL_DOMAIN=$(uci get dhcp.@dnsmasq[0].local| sed 's|/||g')
DHCP_LEASES=/tmp/dhcp.leases

clear_hints() {
	#clear all hints record from kresd
	echo "">$TMP_HINTS_CONFIG_EMPTY
	echo "hints.config('$TMP_HINTS_CONFIG_EMPTY')" | socat - UNIX-CONNECT:$TTY_PATH > /dev/null 2>&1
}

load_dynamic_hints() {

	#init dynamic hints file
	echo "#Do not edit">$TMP_HINTS_CONFIG_DYNAMIC
	echo "#file generated from $TMP_HINTS_CONFIG and $DHCP_LEASES ">>$TMP_HINTS_CONFIG_DYNAMIC

	#copy static hints
	cat $TMP_HINTS_CONFIG>>$TMP_HINTS_CONFIG_DYNAMIC

	#add dhcp dynamic domains
	while read line; do
		ip=$(echo "$line"|awk '{print $3}')
		name=$(echo "$line"|awk '{print $4}')
		if [ "$name" != '*' ]; then
			echo $ip $name.$LOCAL_DOMAIN>>$TMP_HINTS_CONFIG_DYNAMIC
		fi
	done <$DHCP_LEASES

	#load generated hints file
	echo "hints.config('$TMP_HINTS_CONFIG_DYNAMIC')" | socat - UNIX-CONNECT:$TTY_PATH  > /dev/null 2>&1
}

prefered_resolver=$(uci get resolver.common.prefered_resolver)
enable_dynamic_domains=$(uci get resolver.kresd.dynamic_domains)

if [ "$prefered_resolver" == "kresd" ] && [ "$enable_dynamic_domains" == "1" ]; then
	clear_hints
	load_dynamic_hints
fi

