#!/bin/sh
#
# foris-client-wrapper - wrapper around foris-client command
# Copyright (C) 2019 CZ.NIC, z.s.p.o. (http://www.nic.cz/)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
#

# This is a wrapper around foris-client binary
# It takes the same arguments as foris-controller


. $IPKG_INSTROOT/lib/functions.sh

config_load foris-controller

config_get host mqtt host localhost
config_get port mqtt port 11883
config_get credentials_file mqtt credentials_file /etc/fosquitto/credentials.plain
if serial_number=$(crypto-wrapper serial-number); then
	controller_id="--controller-id $serial_number"
fi

exec /usr/bin/foris-client "$@" mqtt --host "$host" --port "$port" --passwd-file "$credentials_file" $controller_id
