#!/bin/sh

base_dir=/tmp/user_notify

usage() {
	echo "This program serves for creating messages which will be send to the user." >&2
	echo "Usage:" >&2
	echo -e "\t $0 -s [restart,error,update,news] 'Czech text of the message' 'English text of the message'" >&2
}

trigger=false

if [ "$1" = -t ] ; then
	trigger=true
	shift
fi

if [ "$1" = -d ] ; then
	base_dir="$2"
	shift 2
fi

if [ $# -eq 3 ]; then
	echo "Backwards compatibility mode: using only single language. Please provide both languages." >&2
	compat=true
elif [ $# -ne 4 ]; then
	usage
	exit 1
else
	compat=false
fi

if [ "$1" = "-s" ]; then
	if [ "$2" = "restart" ] || [ "$2" = "error" ] || [ "$2" = "update" ] || [ "$2" = "news" ] || [ "$2" = "test" ] ; then
		severity="$2"
	else
		usage
		exit 1
	fi
else
	usage
	exit 1
fi

message_cs="$3"
message_en="$4"
# This should be unique
msg_id="$(/bin/busybox date +%s)-$$"

mkdir -p "$base_dir"
mkdir "$base_dir/tmp.$msg_id"
echo "$severity" > "$base_dir/tmp.$msg_id/severity"
if $compat ; then
	echo "$message_cs" > "$base_dir/tmp.$msg_id/message"
else
	echo "$message_cs" > "$base_dir/tmp.$msg_id/message_cs"
	echo "$message_en" > "$base_dir/tmp.$msg_id/message_en"
fi

mv "$base_dir/tmp.$msg_id" "$base_dir/$msg_id"

if $trigger ; then
	exec notifier -d "$base_dir"
fi
