#!/bin/sh

set -e

base_folder=/tmp/user_notify
locker_stamp="$base_folder/.locked"

while ! mkdir "$locker_stamp" ; do
	sleep 1
done

cd "$base_folder"
for i in * ; do
	if [ -d "$base_folder/$i" -a -f "$base_folder/$i/sent_by_email" -a -f "$base_folder/$i/displayed" ] ; then
		rm -rf "$base_folder/$i"
	fi
done

rm -rf "$locker_stamp"
