#
## Copyright (C) 2013-2014 CZ.NIC z.s.p.o. (http://www.nic.cz/)
#
## This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
# #
#

include $(TOPDIR)/package/packages/net/ucollect-prog/Makefile.common

$(eval $(call UCOLLECT_PLUGIN,badconf,22))

$(eval $(call BuildPackage,ucollect-badconf))
