#!/bin/sh /etc/rc.common

START=11
STOP=99

start() {
	ubus call system watchdog '{"magicclose": true}'
	ubus call system watchdog '{"stop": true}'
	watchdog -T 30 -t 5 /dev/watchdog
}

stop() {
	killall watchdog
}
