#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2014 OpenWrt.org
#           (C) CZ.NIC, z.s.p.o.

BIRD="bird6"

START=99
STOP=10

SERVICE_DAEMONIZE=1
SERVICE_USE_PID=1
SERVICE_PID_FILE="/var/run/$BIRD.pid"

BIRD_BIN="/usr/sbin/$BIRD"
BIRD_CONF="/etc/$BIRD.conf"

start() {
	service_start $BIRD_BIN -d -u bird -g bird -c $BIRD_CONF -P $SERVICE_PID_FILE
}

stop() {
	service_stop $BIRD_BIN
}

reload() {
	service_reload $BIRD_BIN
}
