#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh -c 'sentinel-certgen certs && exec sentinel-proxy'
    procd_set_param respawn 600 5 5
    procd_close_instance
}
