#!/bin/sh
set -e

uci -q batch <<EOT
	delete firewall.sentinel_firewall
	set firewall.sentinel_firewall=include
	set firewall.sentinel_firewall.type='script'
	set firewall.sentinel_firewall.path='/usr/libexec/sentinel/firewall.sh'
	set firewall.sentinel_firewall.family='any'
	set firewall.sentinel_firewall.reload='1'
	commit firewall.sentinel_firewall
EOT
# We order include to last position in firewall config. The reason is that
# sentinel potentially can freely modify any firewall rule this way.

# Always reload firewall to use latest version of sentinel-firewall script
/etc/init.d/firewall reload
