#!/bin/sh /etc/rc.common

START=99
STOP=00

start() {
	msg="Router Turris successfully started."
	logger -p 0 -t turris "$msg"
	echo "$msg" > /dev/console
	[ \! -e /sys/class/leds/red/trigger ] || echo heartbeat > /sys/class/leds/red/trigger
}

stop() {
	msg="Stopping router Turris."
	logger -p 0 -t turris "$msg"
	echo "$msg" > /dev/console
	[ \! -e /sys/class/leds/red/trigger ] || echo default-on > /sys/class/leds/red/trigger
}

