#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

USE_PROCD=1

# Start after the updater resume
START=80

restart() {
	stop
	start
}

start_service() {
	mkdir -m 0755 -p /var/log/lighttpd
	procd_open_instance
	procd_set_param command /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
	procd_set_param respawn 120 2 5
	procd_add_mdns "http" "tcp" "80" "daemon=lighttpd"
	procd_add_mdns "https" "tcp" "443" "daemon=lighttpd"
	procd_close_instance
}

