#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

SERVICE_USE_PID=1

# Start after the updater resume
START=86

start() {
	mkdir -m 0755 -p /var/log/lighttpd
	service_start /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf
}

stop() {
	service_stop /usr/sbin/lighttpd
}

restart() {
	/usr/sbin/lighttpd -t -f /etc/lighttpd/lighttpd.conf || exit 1
	ls /usr/lib/lighttpd/mod_alias.so || exit 1
	ls /usr/lib/lighttpd/mod_cgi.so || exit 1
	stop
	start
}
