#!/bin/sh
set -e

CONF=/etc/atsha.sw

if [ -f "$CONF" ]; then
	if head -n1 "$CONF" | grep -q '00 00 00 00' ; then
		# Delete version 1 config, it is no longer supported, and generate new one.
		rm /etc/atsha.sw
	elif head -n18 "$CONF" | tail -n1 | grep -q 'FF FF FF FF' ; then
		# As well for the version 3 config
		rm /etc/atsha.sw
	else
		# Alredy generated
		exit
	fi
fi

#FIXME: Omnia currently doesn't have a mac address at this time
#MAC=$(ifconfig | head -n1 | sed -e 's/.* HWaddr //;s/^..:..//')
MAC=$(dd if=/dev/urandom bs=1 count=4 | hexdump -C | sed -e 's/^[^ ]*//;s/|.*//;s/ //g' | tr '\n' ' ' | tr '[a-z]' '[A-Z]' | sed -e 's/ //g')
touch /tmp/atsha.sw
chmod 0600 /tmp/atsha.sw
for i in `seq 1 16` ; do
	KEY=$(dd if=/dev/urandom bs=1 count=32 | hexdump -C | sed -e 's/^[^ ]*//;s/|.*//;s/ //g' | tr '\n' ' ' | tr '[a-z]' '[A-Z]' | sed -e 's/ //g')
	echo "$KEY" >>/tmp/atsha.sw
done
echo 00 00 00 0A >>/tmp/atsha.sw
echo "$MAC" >>/tmp/atsha.sw
echo 00 00 00 00 >>/tmp/atsha.sw
for i in `seq 1 13` ; do
	echo FF FF FF FF >>/tmp/atsha.sw
done
echo "00 00 00 $MAC" >>/tmp/atsha.sw
chmod 0400 /tmp/atsha.sw

mv /tmp/atsha.sw "$CONF"
