#
## Copyright (C) 2013-2015 CZ.NIC z.s.p.o. (http://www.nic.cz/)
#
## This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
# #
#

include ../ucollect-prog/Makefile.common

$(eval $(call UCOLLECT_PLUGIN,count,28))

$(eval $(call BuildPackage,ucollect-count))
