#!/bin/sh /etc/rc.common

USE_PROCD=1
START=91

start_service() {
  procd_open_instance
  procd_set_param command pakon-handler
  procd_set_param respawn ${respawn_threshold:-600} ${respawn_timeout:-5} ${respawn_retry:-5}
  procd_close_instance
}
