#!/bin/sh /etc/rc.common

START=99
STOP=1

USE_PROCD=1
PROG=/usr/bin/ups-pfc8591-daemon

start_service() {
	procd_open_instance
	procd_set_param respawn
	procd_set_param command "$PROG"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
