#!/bin/sh

dhcp_port=$(uci -q get dhcp.@dnsmasq[0].port)
if [ $? -eq 1 ]; then
	uci set dhcp.@dnsmasq[0].port=0
	touch /etc/resolver/dnsmasq_disabled
fi
# Make sure we can set time for resolution to work, before the resolution works.
uci show system.ntp.server | grep -q '217\.31\.202\.100' || uci add_list system.ntp.server=217.31.202.100
# Also, when we have turned the dnsmasq DNS off, ask dnsmasq to advertise us as DNS server
uci show dhcp | sed -ne 's/^dhcp\.//;s/=dhcp$//p' | while read INTERFACE ; do
	# If the interface has an IP address. Otherwise, just ignore it.
	IP=$(uci -q get network."$INTERFACE".ipaddr)
	if [ -n "$IP" ] ; then
		OPTIONS=$(uci get dhcp."$INTERFACE".dhcp_option | grep "^6,")
		if [ -z "$OPTIONS" ] ; then
			uci -q add_list dhcp."$INTERFACE".dhcp_option="6,$IP"
		fi
	fi
done
uci commit dhcp
uci commit system

# set default DNS resolver and prefer knot-resolver if available
if [ -f "/usr/bin/kresd" ]; then
	uci set resolver.common.prefered_resolver="kresd"
	uci commit resolver
elif [ -f "/usr/sbin/unbound" ]; then
	uci set resolver.common.prefered_resolver="unbound"
	uci commit resolver
else
	logger -t resolver_conf "Error! Could not find resolver! DNS resolving will not work."
fi
