#!/bin/sh /etc/rc.common

USE_PROCD=1
START=25
STOP=80

CERT_KEY="/var/run/dynfw_server.pub"
IPSET="turris-sn-dynfw-block"

start_service() {
	procd_open_instance
	procd_set_param command sentinel-dynfw-client
	procd_append_param command --ipset "$IPSET"
	procd_append_param command --cert "$CERT_KEY"
	procd_append_param command --renew
	procd_set_param stderr 1
	procd_set_param respawn 600 5 5
	procd_close_instance
}
