#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90
STOP=10
EXTRA_COMMANDS="getcert"

CERT_KEY="/tmp/run/sentinel_server.key"

start_service() {
	getcert || {
		echo "Can't download server certificate" >&2
		exit 1
	}

	procd_open_instance
	procd_set_param command sentinel-dynfw-client
	procd_append_param command --ipset "turris-sn-wan-input-block"
	procd_append_param command --cert "$CERT_KEY"
	procd_set_param respawn 600 5 5
	procd_close_instance
}

getcert() {
	[ -f "$CERT_KEY" ] && return 0
	curl -f -s https://repo.turris.cz/sentinel/dynfw.pub -o "$CERT_KEY"
	#TODO: add certificate gpg verification
}
