#!/bin/sh
set -e
. /lib/functions/sentinel-firewall.sh

# Remove old rules
[ -z "$(uci -q get firewall.sentinel_dynfw_client)" ] || \
	uci -q delete firewall.sentinel_dynfw_client
[ -z "$(uci -q get firewall.sentinel_dynfw_client_ipset)" ] || \
	uci -q delete firewall.sentinel_dynfw_client_ipset


# Enable for default wan interface
config_firewall_default_enable "sentinel_dynfw"

# Always reload firewall to use latest version of sentinel-firewall script
/etc/init.d/firewall reload
