#!/bin/sh /etc/rc.common

START=90

USE_PROCD=1

start_service() {
	mkdir -p /var/spool/cron
	ln -sf /etc/crontabs /var/spool/cron/crontabs

	local use_sendmail
	config_load cronie
	config_get_bool use_sendmail cronie sendmail '0'

	procd_open_instance
	procd_set_param command /usr/sbin/crond -n -P
	[ "$use_sendmail" = "1" ] || procd_append_param command -m off -s
	procd_set_param respawn
	procd_set_param file /etc/cron.d/*
	procd_close_instance
}
