#!/bin/sh
# Local repo contains possibly invalid packages so just flush it.

SOURCE="/usr/share/updater/localrepo"
COLLIDED="/usr/share/updater/collided$SOURCE"

if [ -f "$SOURCE/localrepo.lua" ]; then
	mkdir -p "${COLLIDED%/*}"
	mv  "$SOURCE" "$COLLIDED"
fi
