#!/bin/sh
# Local repo contains possibly invalid packages so just flush it.

SOURCE="/usr/share/updater/localrepo"
COLLIDED="/usr/share/updater/collided$SOURCE"

if [ -f "$SOURCE/localrepo.lua" ]; then
	mkdir -p "${COLLIDED%/*}"
	mv  "$SOURCE" "$COLLIDED"
	create_notification -s error \
		"Localrepo was preventively flushed because of binary compatibility. You can found your packages in: $COLLIDED"
fi
