#!/bin/sh
# Updater now in default looks for Packages index instead of Packages.gz index.
# This is because of change done in code. New localrepo generates plain Packages
# indexes but old one generates gzipped ones. This just converts them initially to
# plain ones before localrepo repositories are refactored with localrepo update.

find /usr/share/updater/localrepo -type f -name Packages.gz | while read -r index; do
	zcat "$index" > "${index%.gz}"
done
