#!/bin/sh
. /lib/functions.sh
# netifd provides default network overlay with current runtime configuration. We
# are not interested in that. We need to work with real content of /etc/config so
# we disable state loading.
LOAD_STATE=
config_load network

if [ "$(cat /tmp/sysinfo/model)" = "Turris" ]; then
	# Turris 1.x
	CPU_LAN_1="eth0"
	CPU_TRUNK_1="6"
	CPU_LAN_2="eth1"
	CPU_TRUNK_2="0"
	WAN="eth2"
	NEW_WAN="eth2"
else
	# Turris Omnia
	CPU_LAN_1="eth0"
	CPU_TRUNK_1="5"
	CPU_LAN_2="eth2"
	CPU_TRUNK_2="6"
	WAN="eth1"
	NEW_WAN="eth2"
fi

vlandir="$(mktemp -d)"
cleanup() {
	rm -rf "$vlandir"
}
trap cleanup EXIT TERM INT QUIT ABRT

vlan_handle() {
	local vlan="$1"
	local ports vid
	config_get ports "$vlan" ports
	config_get vid "$vlan" vlan 0
	config_get vid "$vlan" vid "$vid"
	for port in $ports; do
		case "$port" in
			"$CPU_TRUNK_1")
				echo "$vlan" > "$vlandir/$CPU_LAN_1"
				;;
			"${CPU_TRUNK_1}t")
				echo "$vlan" > "$vlandir/$CPU_LAN_1.$vid"
				;;
			"$CPU_TRUNK_2")
				echo "$vlan" > "$vlandir/$CPU_LAN_2"
				;;
			"${CPU_TRUNK_2}t")
				echo "$vlan" > "$vlandir/$CPU_LAN_2.$vid"
				;;
		esac
	done
	# Note: if there is no CPU port then creating new bridge can be solution but
	# at the moment we do not do it as we have routers not smart switches.
}
config_foreach vlan_handle switch_vlan

append_lan_ports() {
	[ -f "$vlandir/$ifn" ] || return # ignore VLANs that are not in switch
	# Note: there can be tagged vlan going to switch but if switch is not
	# configured for it it does not work anyway.

	local vlan ports vid
	vlan="$(cat "$vlandir/$ifn")"
	config_get ports "$vlan" ports
	config_get vid "$vlan" vid
	for port in $ports; do
		case "$port" in
			"$CPU_TRUNK_1"|"${CPU_TRUNK_1}t"|"$CPU_TRUNK_2"|"${CPU_TRUNK_2}t")
				# Ignore CPU ports those are managed by DSA
				;;
			*t)
				append new_ifname "lan${port%t}.${vid}"
				;;
			*)
				append new_ifname "lan${port}"
				;;
		esac
	done
}
interface_handle() {
	local cnf="$1"
	local ifnames new_ifname
	config_get ifnames "$cnf" ifname
	for ifn in $ifnames; do
		case "$ifn" in
			"${CPU_LAN_1}"*|"${CPU_LAN_2}"*)
				append_lan_ports
				;;
			"${WAN}"*)
				# Replace new old wan with new one and keep any VLAN configuration
				append new_ifname "${NEW_WAN}${ifn#${WAN}}"
				;;
			*)
				append new_ifname "$ifn"
				;;
		esac
	done

	uci delete "network.$cnf.ifname"
	case "$new_ifname" in
		*\ *)
			for ifn in $new_ifname; do
				uci add_list "network.$cnf.ifname=$ifn"
			done
			;;
		*)
			uci set "network.$cnf.ifname=$new_ifname"
			;;
	esac
}
config_foreach interface_handle interface


network_section_remove() {
	uci delete "network.$1"
}
config_foreach network_section_remove switch
config_foreach network_section_remove switch_vlan
config_foreach network_section_remove switch_port

uci commit network
