#!/bin/sh /etc/rc.common

START=50
STOP=50

USE_PROCD=1


start_service() {

	procd_open_instance
	procd_set_param command collectd
	procd_append_param command -C /etc/follectd.conf -f
	procd_set_param stdout 1 # forward stdout of the command to logd
	procd_set_param stderr 1 # same for stderr
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-0.2} ${respawn_retry:-25}
	procd_close_instance
}
