#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

SERVICE_USE_PID=1

start() {
	[ -f /etc/syslog-ng.conf ] || return 1
	service_start /usr/sbin/syslog-ng
}

stop() {
	service_stop /usr/sbin/syslog-ng
	# For some reason, the above was leaving processes around.
	# When we say stop, we really do mean stop.
	killall syslog-ng
	true
}

reload() {
	service_reload /usr/sbin/syslog-ng
}
