#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90

start_service() {
  [ -f /srv/pakon/pakon.db.xz ] && xz --stdout -d /srv/pakon/pakon.db.xz > /var/lib/pakon.db
  /usr/bin/sqlite3 /var/lib/pakon.db "pragma integrity_check" >/dev/null || rm -f /var/lib/pakon.db
  procd_open_instance
  procd_set_param command /usr/bin/pakon-monitor
  procd_set_param respawn ${respawn_threshold:-600} ${respawn_timeout:-5} ${respawn_retry:-5}
  procd_close_instance
}

stop_service() {
  mkdir -p /srv/suricata
  [ -f /var/lib/pakon.db ] && /usr/libexec/pakon-light/backup_sqlite.sh /var/lib/pakon.db /srv/pakon/pakon.db.xz 
}
