#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90

start_service() {
  mkdir -p /var/lib
  mkdir -p /srv/suricata
  [ \! -f /srv/suricata/pakon.db.xz ] || xz --stdout -d /srv/suricata/pakon.db.xz > /var/lib/pakon.db
  procd_open_instance
  procd_set_param command /usr/bin/pakon-monitor
  procd_set_param respawn ${respawn_threshold:-600} ${respawn_timeout:-5} ${respawn_retry:-5}
  procd_close_instance
}

stop_service() {
  mkdir -p /srv/suricata
  [ \! -f /var/lib/pakon.db ] || xz -9 --stdout /var/lib/pakon.db > /srv/suricata/pakon.db.xz.tmp && mv /srv/suricata/pakon.db.xz.tmp /srv/suricata/pakon.db.xz
}
