#!/bin/sh
set -e
# Note: there is no `set -u` as jshn.sh is not compatible with it.
. /usr/share/libubox/jshn.sh
. /lib/functions.sh


foris_password() {
	local password
	json_get_var password "foris_password" || {
		echo "foris_password configuration not present. Abandoning initial configuration." >&2
		exit 1
	}

	local pbkdf2
	pbkdf2="$(python -c \
		'import pbkdf2; import sys; print(pbkdf2.crypt(sys.argv[1], iterations=1000))' \
			-- "$password")"
	uci -q batch <<-EOF
		foris.auth=config
		foris.auth.password=$pbkdf2
		commit foris.auth
	EOF
	echo "Foris password set." >&2
}

system_password() {
	local password
	json_get_var password "system_password" || {
		echo "system_password configuration not present." >&2
		return
	}

	echo "root:$password" | chpasswd
	passwd -u root
	echo "System password set." >&2
}

wifi_handle() {
	local iface="$1"
	local device
	config_get device "$iface" device
	uci batch <<-EOF
		set wireless.$iface.ssid=$ssid
		set wireless.$iface.encryption=psk2+ccmp
		set wireless.$iface.key=$key
		set wireless.$device.disabled=0
	EOF
	echo "Wireless configured on device: $device" >&2
}

wireless() (
	json_select "wireless" >/dev/null || {
		echo "wireless configuration not present." >&2
		return 0
	}
	local ssid key
	for var in ssid key; do
		json_get_var "$var" "$var" || {
			echo "wireless.$var configuration is missing. Wireless configuration not performed." >&2
			return 0
		}
	done

	config_load wireless
	config_foreach wifi_handle wifi-iface
	if [ -n "$(uci changes wireless)" ]; then
		uci commit wireless
	else
		echo "Wireless configuration is not possible as there is no Wi-Fi device." >&2
	fi
)


locate_config() {
	local config_file
	for dev in /dev/mmcblk*p* /dev/sd*; do
		[ -e "$dev" ] || continue
		echo "Checking device: $dev" >&2
		mount "$dev" "$tmpmnt" || continue

		config_file="$tmpmnt/medkit-config.json"
		if [ -f "$config_file" ]; then
			echo "Located config file: ${config_file##*/}" >&2
			break
		fi

		umount -fl "$tmpmnt"
	done
	[ -z "$config_file" ] && return 1
	echo "$config_file"
}

main() {
	local config_file
	config_file="$(locate_config)" || {
		echo "Device with config file not located." >&2
		exit 0
	}

	# Load config and apply it on system
	json_init
	json_load_file "$config_file"

	foris_password
	system_password
	wireless

	umount -fl "$tmpmnt"
}


tmpmnt="$(mktemp -d)"
tmpclean() {
	umount -fl "$tmpmnt" 2>/dev/null || true
	rmdir "$tmpmnt" 2>/dev/null || true
}
trap tmpclean HUP INT QUIT TERM EXIT

main
