#!/bin/sh /etc/rc.common

START=19
USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /usr/sbin/sfpswitch.py --nodaemon
  procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
  procd_set_param stdout 1 # forward stdout of the command to logd
  procd_set_param stderr 1 # same for stderr
  procd_close_instance
}

