#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10
EXTRA_COMMANDS="check_fw"

iptables_ensure(){
	iptables -C $@ 2>/dev/null || iptables -I $@
}

check_fw() {
	FW_SETUP="`uci -q get haas.settings.setup_fw | egrep -i '(1|yes|true|enabled|on)'`"
	PORT="`uci -q get haas.settings.local_port`"
	WAN_IP="`ubus call network.interface.wan status | sed -n 's|.*address":[[:blank:]]*"\([0-9.]*\)".*|\1|p'`"
	if [ -n "$FW_SETUP" -a -n "$PORT" ]; then
		if [ -n "$WAN_IP" ]; then
			iptables_ensure zone_wan_prerouting -t nat -p tcp -m tcp --dport 22 -m comment --comment "haas" -j DNAT --to-destination $WAN_IP:$PORT
			iptables_ensure zone_wan_prerouting -t nat -p tcp -m tcp --dport 22 -j MARK --set-mark 0x10
			echo "iptables -t nat -D zone_wan_prerouting -p tcp -m tcp --dport 22 -m comment --comment \"haas\" -j DNAT --to-destination $WAN_IP:$PORT" > /tmp/haas-remove-iptables
			echo "iptables -t nat -D zone_wan_prerouting -p tcp -m tcp --dport 22 -j MARK --set-mark 0x10" >> /tmp/haas-remove-iptables
		else
			( sleep 60 && /etc/init.d/haas-proxy check_fw ) &
		fi
	fi
	[ \! -e /sys/fs/cgroup/haas/tasks ] || cat /tmp/haas.pid 2> /dev/null > /sys/fs/cgroup/haas/tasks
}

start_service() {
	TOKEN="`uci -q get haas.settings.token`"
	LOG_LEVEL="`uci -q get haas.settings.log_level`"
	PORT="`uci -q get haas.settings.local_port`"
	FW_SETUP="`uci -q get haas.settings.setup_fw | egrep -i '(1|yes|true|enabled|on)'`"
	LOG="`uci -q get haas.settings.log`"
	if [ -z "$LOG" ] || [ "$LOG" = none ]; then
		LOG=""
	else
		LOG="--log-file=$LOG"
	fi
	[ -n "$TOKEN" ] || exit 1
	[ -n "$LOG_LEVEL" ] || LOG_LEVEL="warning"
	check_fw
	CGROUPS="`test -f /sys/fs/cgroup/cpu.shares && echo YES`"
	if [ -n "$CGROUPS" ]; then
		echo 1 > /sys/fs/cgroup/cgroup.clone_children
		mkdir -p /sys/fs/cgroup/haas
		echo 128 > /sys/fs/cgroup/haas/cpu.shares
		echo 1000000 > /sys/fs/cgroup/haas/cpu.cfs_period_us
		echo  150000 > /sys/fs/cgroup/haas/cpu.cfs_quota_us
	fi
	procd_open_instance
	procd_set_param command /usr/bin/python2.7 -m haas_proxy -n --pidfile=/tmp/haas.pid haas_proxy $LOG --log-level "$LOG_LEVEL" --device-token $TOKEN --port $PORT
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param file /etc/config/haas
	procd_close_instance
	sleep 5 && cat /tmp/haas.pid 2> /dev/null > /sys/fs/cgroup/haas/tasks &
	sleep 120 && cat /tmp/haas.pid 2> /dev/null > /sys/fs/cgroup/haas/tasks &
}

stop_service() {
	FW_SETUP="`uci -q get haas.settings.setup_fw | egrep -i '(1|yes|true|enabled|on)'`"
	if [ "$FW_SETUP" ] && [ -f /tmp/haas-remove-iptables ]; then
		sh /tmp/haas-remove-iptables
		rm -f /tmp/haas-remove-iptables
	fi
	if [ -f /tmp/haas.pid ]; then
		kill `cat /tmp/haas.pid 2>/dev/null` > /dev/null 2>&1
		sleep 1
		kill -9 `cat /tmp/haas.pid 2>/dev/null` > /dev/null 2>&1
		rm -f /tmp/haas.pid
	fi
}
