#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10
EXTRA_COMMANDS="check_fw"

iptables_ensure(){
	iptables -C $@ 2>/dev/null || iptables -I $@
}

check_fw() {
	FW_SETUP="`uci -q get haas.settings.setup_fw | egrep -i '(1|yes|true|enabled|on)'`"
	PORT="`uci -q get haas.settings.local_port`"
	WAN_IP="`ubus call network.interface.wan status | sed -n 's|.*address":[[:blank:]]*"\([0-9.]*\)".*|\1|p'`"
	if [ -n "$FW_SETUP" -a -n "$PORT" ]; then
		if [ -n "$WAN_IP" ]; then
			iptables_ensure zone_wan_prerouting -t nat -p tcp -m tcp --dport 22 -m comment --comment "haas" -j DNAT --to-destination $WAN_IP:$PORT
			iptables_ensure zone_wan_prerouting -t nat -p tcp -m tcp --dport 22 -j MARK --set-mark 0x10
			echo "iptables -t nat -D zone_wan_prerouting -p tcp -m tcp --dport 22 -m comment --comment \"haas\" -j DNAT --to-destination $WAN_IP:$PORT" > /tmp/haas-remove-iptables
			echo "iptables -t nat -D zone_wan_prerouting -p tcp -m tcp --dport 22 -j MARK --set-mark 0x10" >> /tmp/haas-remove-iptables
		else
			( sleep 60 && $0 check_fw ) &
		fi
	fi
}

start_service() {
	TOKEN="`uci -q get haas.settings.token`"
	PORT="`uci -q get haas.settings.local_port`"
	FW_SETUP="`uci -q get haas.settings.setup_fw | egrep -i '(1|yes|true|enabled|on)'`"
	LOG="`uci -q get haas.settings.log`"
	if [ "$LOG" = syslog ]; then
		LOG="--syslog"
	elif [ -z "$LOG" ] || [ "$LOG" = none ]; then
		LOG=""
	else
		LOG="--logfile=$LOG"
	fi
	[ "$TOKEN" ] || exit 1
	check_fw
	procd_open_instance
	procd_set_param command /usr/bin/python2.7 -m haas_proxy -n --pidfile=/tmp/haas.pid $LOG haas_proxy --device-token $TOKEN --port $PORT
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param file /etc/config/haas
	procd_close_instance
}

stop_service() {
	FW_SETUP="`uci -q get haas.settings.setup_fw | egrep -i '(1|yes|true|enabled|on)'`"
	if [ "$FW_SETUP" ] && [ -f /tmp/haas-remove-iptables ]; then
		sh /tmp/haas-remove-iptables
		rm -f /tmp/haas-remove-iptables
	fi
}
