#!/bin/sh
set -e
. /lib/functions/sentinel-firewall.sh

# Nikola entry in sentinel config
if [ "$(uci -q get sentinel.nikola)" != "nikola" ]; then
	uci -q batch <<EOT
		delete sentinel.nikola
		set sentinel.nikola='nikola'
		commit sentinel.nikola
EOT
fi


# Enable for default interface
config_firewall_default_enable "sentinel_fwlogs"

# Always reload firewall to use latest version of sentinel-firewall script
/etc/init.d/firewall reload
