#!/bin/sh
modules="`ls -1 /sys/bus/moxtet/devices`"

# First setup
if [ \! -f /etc/mox_modules ]; then

	# Drop all network configuration
	uci delete network.lan
	uci delete network.wan

	lans="$(cd /sys/class/net/; echo lan* 2> /dev/null)"
	wan_if=""
	lan_if=""
	lan_mac="$(cat /sys/class/net/eth1/address)"

	# If we have SFP, it is definitely WAN
	if expr "$modules" : '.*sfp.*' > /dev/null && [ -z "$lans" ]; then
		wan_if=sfp
		lan_if="eth0"

	# If we have switch, then CPU port is obviously WAN
	elif expr "$modules" : '.*topaz.*' > /dev/null || expr "$modules" : '.*peridot.*' > /dev/null; then
		wan_if=eth0
		lan_if="$lans"

	# If we have just one port, it has to be LAN
	else
		lan_if="eth0"
		lan_mac="$(cat /sys/class/net/eth0/address)"
	fi

	uci set network.wan=interface
	uci set network.wan.ifname="$wan_if"
	uci set network.wan.proto=none

	uci set network.lan=interface
	uci set network.lan.type=bridge
	uci set network.lan.macaddr="$lan_mac"
	uci set network.lan.ifname="$lan_if"
	uci set network.lan.proto=none
	uci commit
	/etc/init.d/network restart

	# Try dhcpp on LAN after interfaces settle a little bit
	sleep 5
	if [ -z "$wan_if" ] && udhcpc -fqnR -i br-lan; then
		uci set network.lan.proto=dhcp
		uci set network.lan._turris_mode=unmanaged
	else
		uci set network.lan.proto=static
		uci set network.lan.ipaddr=192.168.1.1
		uci set network.lan.netmask=255.255.255.0
		uci set network.lan._turris_mode=managed
		uci set network.lan.ip6assign='60'
	fi
	uci commit
	/etc/init.d/network restart
	echo "$modules" > /etc/mox_modules

# Modules changes
elif [ "`cat /etc/mox_modules`" \!= "$modules" ]; then
	added="`echo "$modules" | comm -23 - /etc/mox_modules | grep '[^[:blank:]]'`"
	removed="`echo "$modules" | comm -13 - /etc/mox_modules | grep '[^[:blank:]]'`"
	TEXT="Your MOX HW configuration changed!"
	[ -z "$added" ] || TEXT="$TEXT You added `echo $added` module(s)."
	[ -z "$removed" ] || TEXT="$TEXT You removed `echo $removed` module(s)."
	TEXT="$TEXT Make sure that your setup is correct or try factory reset for new setup."
	create_notification -s news "$TEXT"
	if ( expr "$added" : '.*topaz.*' > /dev/null || expr "$added" : '.*peridot.*' > /dev/null ) && [ -n "`uci show network.lan`" ]; then
		for iface in `cd /sys/class/net/; ls -d lan* 2> /dev/null`; do
			[ -n "`uci show network | grep "\.ifname=.*$iface"`" ] || uci set network.lan.ifname="`uci get network.lan.ifname` $iface"
		done
	fi
	uci commit
	/etc/init.d/network restart
	echo "$modules" > /etc/mox_modules
fi
