#!/bin/sh
if [ "`cat /proc/mounts | grep '^/dev/mmcblk0p2 / btrfs'`" ]; then
	mkdir -p /boot/tefi
	mount -t vfat /dev/mmcblk0p1 /boot/tefi
	cmp "$1"/boot/zImage /boot/tefi/zImage || cp "$1"/boot/zImage /boot/tefi/zImage
	cmp "$1"/boot/fdt /boot/tefi/fdt || cp "$1"/boot/fdt /boot/tefi/fdt
	umount /boot/tefi
fi
