#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

get_cert() {
    /usr/bin/python3 /usr/libexec/sentinel_certgen.py certs --cert-api-hostname 'sentinel.turris.cz'
}

start_service() {
    get_cert

    procd_open_instance
    procd_set_param command /usr/bin/sentinel-proxy
    procd_set_param respawn ${respawn_threshold:-600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_close_instance
}
