#!/bin/sh
set -e

uci -q batch <<EOT
	delete firewall.redirect_192_168_1_1
	set firewall.redirect_192_168_1_1=include
	set firewall.redirect_192_168_1_1.type='script'
	set firewall.redirect_192_168_1_1.path='/usr/libexec/firewall-redirect-192-168-1-1.sh'
	set firewall.redirect_192_168_1_1.family='ipv4'
	set firewall.redirect_192_168_1_1.reload='1'
	commit firewall.sentinel_firewall
EOT

# Always reload firewall to use latest version
/etc/init.d/firewall reload
