#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90

start_service() {
  mkdir -p /var/lib
  mkdir -p /srv/suricata
  [ \! -f /srv/suricata/suricata-monitor.db ] || cp /srv/suricata/suricata-monitor.db /var/lib
  procd_open_instance
  procd_set_param command /usr/bin/suricata-monitor
  procd_set_param file /etc/config/suricata-monitor
  procd_set_param respawn ${respawn_threshold:-600} ${respawn_timeout:-5} ${respawn_retry:-5}
  procd_close_instance
}

stop_service() {
  mkdir -p /srv/suricata
  [ \! -f /var/lib/suricata-monitor.db ] || cp /var/lib/suricata-monitor.db /srv/suricata
}
