#!/bin/sh

# Thanks to the bug in busybox sometimes uci-default script doesn't work

PASS=`grep root /etc/shadow | cut -d ':' -f2`

if [ $PASS == "x" ]; then
    DUMMY_PASS=`tr -dc A-Za-z0-9_ < /dev/urandom | head -c 64`
    echo -e "${DUMMY_PASS}\n${DUMMY_PASS}" | passwd root
fi

