#!/bin/sh
set -e
set -u

# uci wrapper to silently get the value of $1 option and return success
silent_uci_get() {
    uci -q get "$1" || true
}

# Check global section
get_global=$(silent_uci_get mwan3.globals)
if [ "$get_global" == "globals" ]; then
        echo "mwan3: Globals section is ok"
else
        # set globals
        uci set mwan3.globals=globals
fi

if [ -z "$(silent_uci_get mwan3.globals.mmx_mask)" ]; then
        uci set mwan3.globals.mmx_mask='0x3F00'
fi
if [ -z "$(silent_uci_get mwan3.globals.rtmon_interval)" ]; then
        uci set mwan3.globals.rtmon_interval='5'
fi

if [ -z "$(silent_uci_get mwan3.globals.enabled)" ]; then
        uci set mwan3.globals.enabled='1'
fi

if [ -z "$(silent_uci_get mwan3.globals.loglevel)" ]; then
        uci set mwan3.globals.loglevel='0'
fi

# Check family setting
uci show mwan3 | awk -F '=' '$2 == "interface" { print $1 }' \
    | while read -r i; do
        family=$(silent_uci_get $i.family) || true

        if [ "$family" == "ipv4" -o "$family" == "ipv6" ]; then
                echo "mwan3: $i family ok"
        else
                uci set $i.family="ipv4"
                echo "mwan3 setting family"
        fi

        track_method=$(silent_uci_get $i.track_method)
        if [ -z "$track_method" ]; then
                # set ping track method
                echo "mwan3 setting $i track method ping"
                uci set $i.track_method="ping"
        fi

done

uci commit mwan3
