#!/bin/sh
if [ "$(uname -m)" = "armv7l" ] && \
   [ -z "$(uci show system | grep '@led.*.sysfs=.omnia-led:wan.')" ] && \
   [ -d "/sys/class/leds/omnia-led:wan" ] && \
   [ -n "$(uci get network.wan.ifname)" ]; then
	uci set system.led_wan="led"
	uci set system.led_wan.name="Auto-configuration for WAN"
	uci set system.led_wan.sysfs="omnia-led:wan"
	uci commit
	/etc/init.d/led_autoconfig restart
fi
