#!/bin/sh

. /lib/functions.sh

config_load foris
config_get_bool WIZARD_FINISHED wizard finished "0"
config_get SCRIPTNAME server scriptname "/foris"

SCRIPTNAME=$(echo "$SCRIPTNAME" | sed -e 's;\\;\\\\;g' | sed -e 's;/*$;;g' | sed -e 's;^/*;;g' | sed -e 's;/+;/;g')

if [ $WIZARD_FINISHED = "1" ]; then
  APP="config"
else
  APP="wizard"
fi

cat << HTML
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Cache-Control" content="no-cache" />
		<meta http-equiv="refresh" content="0; URL=$SCRIPTNAME/$APP/" />
	</head>
	<body style="background-color: white">
		<a style="color: black; font-family: arial, helvetica, sans-serif;" href="$SCRIPTNAME/$APP/">Foris - $APP</a>
	</body>
</html>
HTML
