#!/bin/sh

. /lib/functions.sh

config_load foris
config_get_bool DEBUG server debug "0"
config_get_bool NOAUTH auth noauth "0"

EXTRA_FLAGS=""
[ "$DEBUG" == "1" ] && EXTRA_FLAGS="$EXTRA_FLAGS -d"
[ "$NOAUTH" == "1" ] && EXTRA_FLAGS="$EXTRA_FLAGS --noauth"

exec /usr/bin/foris -s cgi $EXTRA_FLAGS
