#!/bin/sh

. /lib/functions.sh

config_load foris
config_get_bool DEBUG server debug "0"
config_get_bool NOAUTH auth noauth "0"
config_get SESSION_TIMEOUT auth session_timeout ""
config_get SCRIPTNAME server scriptname "/foris"

EXTRA_FLAGS=""
[ "$DEBUG" == "1" ] && EXTRA_FLAGS="$EXTRA_FLAGS -d"
[ "$NOAUTH" == "1" ] && EXTRA_FLAGS="$EXTRA_FLAGS --noauth"
[ "$SESSION_TIMEOUT" != "" ] && EXTRA_FLAGS="$EXTRA_FLAGS --session-timeout $SESSION_TIMEOUT"

if [ -z "$SCRIPTNAME" ]; then
	export PATH_INFO="/"
fi

config_load foris-controller
config_get BUS main bus "ubus"
case "$BUS" in
	ubus)
		config_get BUS_PATH ubus path "/var/run/ubus.sock"
		;;
	unix)
		config_get BUS_PATH unix path "/var/run/foris-controller.sock"
		BUS="unix-socket"
		;;
esac

exec /usr/bin/foris -s cgi $EXTRA_FLAGS -b "$BUS" --backend-socket "$BUS_PATH" -a config
