#!/bin/sh

. /lib/functions.sh

config_load foris
config_get SCRIPTNAME server scriptname "/"
config_get_bool DEBUG server debug "0"
config_get_bool NOAUTH auth noauth "0"
config_get SESSION_TIMEOUT auth session_timeout ""
config_get SERVER server server "flup"

# scriptname must not contain escape codes (avoid CRLF injection in sed later)
# and for the sake of UX, trailing and leading slashes are trimmed
SCRIPTNAME=$(echo "$SCRIPTNAME" | sed -e 's;\\;\\\\;g' | sed -e 's;/*$;;g' | sed -e 's;^/*;;g' | sed -e 's;/+;/;g')
[ "$SCRIPTNAME" != "" ] && SCRIPTNAME="/$SCRIPTNAME"

EXTRA_FLAGS=""
[ "$DEBUG" == "1" ] && EXTRA_FLAGS="$EXTRA_FLAGS -d"
[ "$NOAUTH" == "1" ] && EXTRA_FLAGS="$EXTRA_FLAGS --noauth"
[ "$SESSION_TIMEOUT" != "" ] && EXTRA_FLAGS="$EXTRA_FLAGS --session-timeout $SESSION_TIMEOUT"
EXTRA_FLAGS="$EXTRA_FLAGS -s $SERVER"

FORIS_PATHS=""
tmp_out=$(eval /usr/bin/foris -R $EXTRA_FLAGS)
for path in $tmp_out;  do
	FORIS_PATHS="$FORIS_PATHS|${path:1}"  # remove first '/' character
done


echo 'var.foris.bin = "/usr/bin/foris"'
echo 'var.foris.cgi = "/usr/share/foris/foris-cgi"'
echo "var.foris.scriptname = \"$SCRIPTNAME\""
echo "var.foris.paths = \"$FORIS_PATHS\""
echo "var.foris.flags = \"$EXTRA_FLAGS\""
echo
echo '$HTTP["url"] =~ "^" + var.foris.scriptname + "/(" + var.foris.paths + ")$" {'
case $SERVER in
	flup)
		echo '	fastcgi.debug = 0'
		echo '	fastcgi.server = ('
		if [ -z "$SCRIPTNAME" ] ; then
		echo '		"/" => ('
		else
		echo '		var.foris.scriptname => ('
		fi
		echo '			"python-fcgi" => ('
		echo '				"socket" => "/tmp/fastcgi.python.socket",'
		echo '				"bin-path" => var.foris.bin + var.foris.flags,'
		[ -z "$SCRIPTNAME" ] && echo '				"fix-root-scriptname" => "enable",'
		echo '				"check-local" => "disable",'
		echo '				"max-procs" => 1,'
		echo '			)'
		echo '		)'
		echo '	)'
	;;
	cgi)
		echo '	alias.url = ( var.foris.scriptname => var.foris.cgi )'
		echo '	cgi.assign = ( "" => "" )'
	;;
esac
echo "}"


PLUGINS_DIR=/usr/share/foris/plugins

for PLUGIN_PATH in $PLUGINS_DIR/*; do
	PLUGIN_NAME=$(basename $PLUGIN_PATH)
	[ -d "$PLUGIN_PATH/static" ] && {
		echo "alias.url += ( var.foris.scriptname + \"/plugins/$PLUGIN_NAME/static/\" => \"$PLUGIN_PATH/static/\" )"
	}
done

echo 'alias.url += ( var.foris.scriptname + "/static/" => "/usr/lib/python2.7/site-packages/foris/static/" )'
