#!/bin/sh

. /lib/functions.sh

config_load foris
config_get SCRIPTNAME server scriptname "/foris"
config_get_bool DEBUG server debug "0"
config_get_bool NOAUTH auth noauth "0"
config_get SESSION_TIMEOUT auth session_timeout ""
config_get SERVER server server "flup"

APP="$1"

# scriptname must not contain escape codes (avoid CRLF injection in sed later)
# and for the sake of UX, trailing and leading slashes are trimmed
SCRIPTNAME=$(echo "$SCRIPTNAME" | sed -e 's;\\;\\\\;g' | sed -e 's;/*$;;g' | sed -e 's;^/*;;g' | sed -e 's;/+;/;g')
[ "$SCRIPTNAME" != "" ] && SCRIPTNAME="/$SCRIPTNAME"

EXTRA_FLAGS=""
[ "$DEBUG" == "1" ] && EXTRA_FLAGS="$EXTRA_FLAGS -d"
[ "$NOAUTH" == "1" ] && EXTRA_FLAGS="$EXTRA_FLAGS --noauth"
[ "$SESSION_TIMEOUT" != "" ] && EXTRA_FLAGS="$EXTRA_FLAGS --session-timeout $SESSION_TIMEOUT"
EXTRA_FLAGS="$EXTRA_FLAGS -s $SERVER"

FORIS_PATHS=""
tmp_out=$(eval /usr/bin/foris -R $EXTRA_FLAGS -a $APP)
for path in $tmp_out;  do
	FORIS_PATHS="$FORIS_PATHS|${path:1}"  # remove first '/' character
done


echo "var.foris-$APP.bin = \"/usr/bin/foris\""
echo "var.foris-$APP.cgi = \"/usr/share/foris/foris-$APP-cgi\""
echo "var.foris-$APP.scriptname = \"$SCRIPTNAME/$APP\""
echo "var.foris-$APP.flags = \"$EXTRA_FLAGS -a $APP\""
echo "var.foris-$APP.paths = \"$FORIS_PATHS\""
echo
echo "\$HTTP[\"url\"] =~ \"^\" + var.foris-$APP.scriptname + \"/(\" + var.foris-$APP.paths + \")$\" {"
case $SERVER in
	flup)
		echo '	fastcgi.debug = 0'
		echo '	fastcgi.server = ('
		echo "		var.foris-$APP.scriptname => ("
		echo '			"python-fcgi" => ('
		echo "				\"socket\" => \"/tmp/fastcgi.foris-$APP.socket\","
		echo "				\"bin-path\" => var.foris-$APP.bin + var.foris-$APP.flags,"
		echo '				"check-local" => "disable",'
		echo '				"max-procs" => 1,'
		echo '			)'
		echo '		)'
		echo '	)'
	;;
	cgi)
		echo "	alias.url = ( var.foris-$APP.scriptname => var.foris-$APP.cgi )"
		echo '	cgi.assign = ( "" => "" )'
	;;
esac
echo "}"


PLUGINS_DIR=/usr/share/foris/plugins

for PLUGIN_PATH in $PLUGINS_DIR/*; do
	PLUGIN_NAME=$(basename $PLUGIN_PATH)
	[ -d "$PLUGIN_PATH/static" ] && {
		echo "alias.url += ( var.foris-$APP.scriptname + \"/static/plugins/$PLUGIN_NAME/\" => \"$PLUGIN_PATH/static/\" )"
	}
done

echo "alias.url += ( var.foris-$APP.scriptname + \"/static/\" => \"/usr/lib/python2.7/site-packages/foris/static/\" )"
