#!/bin/sh
set -e

dhparam="/etc/ssl/ca/openvpn/dhparam.pem"

if ! uci get openvpn.server_turris >/dev/null 2>&1; then
	exit 0
fi

turris-cagen switch openvpn link_dh

uci set openvpn.server_turris.dh="$dhparam"
uci commit openvpn.server_turris.dh
