#!/bin/sh
. /lib/functions.sh
config_load updater


add_list() {
	uci get pkglists.pkglists.list | grep -Eq "(^| )$1( |$)" || return 0
	uci add_list pkglists.pkglists.list="$1"
}

set_option() {
	add_list "$1"
	uci set "pkglists.$1=pkglist"
	uci set "pkglists.$1.$2=${3:-1}"
}


pkglist_handle() {
	local lst="$1"
	case "$lst" in
		dev-detect)
			set_option net_monitoring dev_detect
			;;
		honeypot)
			set_option datacollect haas
			;;
		luci-controls)
			# These were removed from package list
			{
				echo 'Install("luci-app-mjpg-streamer")'
				echo 'Install("luci-proto-openconnect")'
				echo 'Install("luci-proto-vpnc")'
			} >> /etc/updater/conf.d/opkg-auto.lua
			# Enable all original features
			set_option luci_controls adblock
			set_option luci_controls sqm
			set_option luci_controls tinyproxy
			set_option luci_controls upnp
			set_option luci_controls statistics
			;;
		nas)
			# Enable all original features
			set_option nas samba
			set_option nas dlna
			set_option nas transmission
			set_option nas raid
			set_option nas encrypt
			;;
		netmetr)
			set_option net_monitoring netmetr
			;;
		pakon)
			set_option net_monitoring pakon
			;;
		printserver)
			set_option luci_controls printserver
			;;
		*)
			add_list "$lst"
			;;
	esac
}
config_list_foreach turris pkglists pkglist_handle
uci delete updater.pkglists

uci commit pkglists

# Remove old config
uci delete updater.turris.pkglists
uci commit updater
