#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10

DEFAULT_TELNET_PORT=2333

start_service() {
	config_load sentinel

	local enabled
	config_get_bool enabled minipot enabled "0"
	[ "$enabled" = "1" ] || return 0

	ps -C sentinel-proxy >/dev/null || return 0

	local telnet_port
	config_get telnet_port minipot telnet_port "$DEFAULT_TELNET_PORT"

	procd_open_instance
	procd_set_param command /usr/bin/sentinel-minipot
	[ "$telnet_port" = "0" ] || procd_append_param command -T "$telnet_port"
	procd_set_param respawn 3600 5 5
	procd_set_param file /etc/config/sentinel
	procd_close_instance
}
